# Generated by Django 5.2 on 2025-04-22 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flower',
            name='is_on_sale',
            field=models.BooleanField(default=False),
        ),
    ]
