# Generated by Django 5.2 on 2025-04-22 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0002_flower_is_on_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='flower',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, default=False, max_digits=10),
        ),
    ]
