# Generated by Django 5.2 on 2025-04-22 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0004_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='customer',
            new_name='user',
        ),
    ]
