# Generated by Django 5.2 on 2025-04-26 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0009_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userorder',
            name='orderitems',
            field=models.CharField(default=0, max_length=400),
        ),
        migrations.AddField(
            model_name='userorder',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='userorder',
            name='user',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
