# Generated by Django 5.2 on 2025-04-26 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0011_order_delete_userorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
