# Generated by Django 5.2 on 2025-04-26 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0013_remove_order_cart_remove_order_name_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='flower',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usermanagement.flower'),
        ),
    ]
